spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/calorine}
spring.datasource.username=${DATABASE_USERNAME:calorine}
spring.datasource.password=${DATABASE_PASSWORD:calorine}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
