ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS review_requested_at TIMESTAMP;
ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS review_notification VARCHAR(220);

CREATE TABLE IF NOT EXISTS product_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES users(id),
  product_id BIGINT NOT NULL REFERENCES candle_product(id),
  order_id BIGINT NOT NULL REFERENCES customer_orders(id),
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment VARCHAR(280) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_product_review_order UNIQUE (customer_id, product_id, order_id)
);
