CREATE TABLE IF NOT EXISTS discount_coupon (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  type VARCHAR(20) NOT NULL,
  coupon_value NUMERIC(10, 2) NOT NULL DEFAULT 0,
  minimum_subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0,
  usage_limit INTEGER,
  used_count INTEGER NOT NULL DEFAULT 0,
  valid_until DATE,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

MERGE INTO discount_coupon (code, type, coupon_value, minimum_subtotal, usage_limit, used_count, valid_until, active)
KEY (code)
VALUES ('CALORINE10', 'PERCENTAGE', 10.00, 0.00, NULL, 0, NULL, TRUE);

MERGE INTO discount_coupon (code, type, coupon_value, minimum_subtotal, usage_limit, used_count, valid_until, active)
KEY (code)
VALUES ('FRETEGRATIS', 'FREE_SHIPPING', 0.00, 180.00, NULL, 0, NULL, TRUE);
